<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => '金额',
    'Amount Refunded' => '退款金额',
    'Batch Deletion' => '批量删除',
    'Canceled At' => '撤销时间',
    'Create Transaction Withdrawal' => '创建提现请求',
    'Delete Transaction Withdrawal' => '删除提现请求',
    'Exceeded the maximum transfer amount.' => '',
    'Extra' => '',
    'ID' => '',
    'Insufficient balance.' => '余额不足。',
    'Manage Transaction Withdrawal' => '提现管理',
    'Order No' => '订单号',
    'Recipient' => '',
    'Recipient Balance Transaction' => '',
    'Recipient ID' => '',
    'Refunded' => '退款',
    'Source Id' => '',
    'Status' => '状态',
    'Succeeded At' => '成功时间',
    'Transaction Type' => '交易类型',
    'Unknown User \'{user}\'' => '',
    'Update Transaction Withdrawal' => '',
    'User Balance Transaction ID' => '',
    'User Fee' => '服务费',
    'User Id' => '',
    'Withdrawal' => '提现',
    'Withdrawal Failed' => '提现失败',
    'Withdrawal Revoked' => '提现撤销',
    'Balance' => '余额',
    'Balance Bonus' => '余额赠送',
    'Balance Transaction ID' => '交易ID',
    'Channel' => '提现渠道',
    'Channel Identity' => '渠道标识',
    'Charge ID' => '支付ID',
    'Charge Order No' => '支付订单号',
    'Charge Transaction No' => '支付平台流水号',
    'Created At' => '创建时间',
    'Description' => '描述',
    'Failure Msg' => '失败消息',
    'Metadata' => '元数据',
];
